[project]
name = "visualsgeneration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-anthropic>=0.3.15",
    "langchain-openai>=0.3.25",
    "langgraph>=0.4.9",
    "manim>=0.19.0",
    "chainlit>=1.0.0",
]
